version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: Django/Dockerfile
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./Django:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  scraper:
    build:
      context: .
      dockerfile: Scraper/Dockerfile
    container_name: scraper_app
    command: python Main.py
    env_file:
      - .env
    volumes:
      - ./Scraper:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Stock
      MYSQL_USER: StockInsertion
      MYSQL_PASSWORD: StockDataInsertion
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
