# Generated by Django 5.2.5 on 2025-08-25 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=10, unique=True)),
                ('companyname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='StockExchange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exchangename', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'StockExchange',
            },
        ),
        migrations.CreateModel(
            name='DayValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.IntegerField()),
                ('trades', models.IntegerField()),
                ('turnover', models.DecimalField(decimal_places=2, max_digits=10)),
                ('companyid', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='stocks.company')),
            ],
            options={
                'db_table': 'DayValue',
                'unique_together': {('companyid', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StockExchangeEntering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofentry', models.DateField()),
                ('dateofexit', models.DateField(blank=True, null=True)),
                ('companyid', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='stocks.company')),
                ('stockexchangeid', models.ForeignKey(db_column='StockExchangeID', on_delete=django.db.models.deletion.CASCADE, to='stocks.stockexchange')),
            ],
            options={
                'db_table': 'StockExchangeEntering',
                'unique_together': {('stockexchangeid', 'companyid')},
            },
        ),
    ]
