# Generated by Django 5.2.5 on 2025-09-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        # All AddField operations removed because the columns already exist in the DB
    ]
