FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc libpq-dev default-libmysqlclient-dev pkg-config \
    && rm -rf /var/lib/apt/lists/*

COPY req.txt /app/req.txt
RUN pip install --no-cache-dir -r /app/req.txt

COPY Scraper/ /app/

CMD ["python", "Main.py"]
